apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  PUBLIC_URL: /
  MERCURE_PUBLISH_URL: https://mercure.dev.ats-digital.com/.well-known/mercure
  APP_ENV: prod
  HOST: olympiqs.local
  ADMIN_HOST: olympiqs-adm.local
  PUBLIC_API_HOST: api.olympiqs.com
  ORGANIZATION: default
  PUBLIC_ORGANIZATION: default
  MONGODB_URL: mongodb://mongo-service
  MONGODB_DB: olympiqs
  MONGODB_REPLICASET: olympiqs
  MONGODB_USERNAME: root
  MONGODB_PASSWORD: root
  OAUTH2_PRIVATE_KEY: /app/certificates/.ssl/private.key
  OAUTH2_PUBLIC_KEY: /app/certificates/.ssl/private.key
  MONGODB_REPLICA_SET_MODE: primary
  MONGODB_REPLICA_SET_NAME: olympiqs
  MONGODB_REPLICA_SET_KEY: rsKey0